# frozen_string_literal: true
ruby '2.3.1'

source 'https://rubygems.org' do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rails-console'
  gem 'capistrano-rbenv'
  gem 'capistrano3-puma', github: 'seuros/capistrano-puma'
end
